---    
apiVersion: v1
kind: Service
metadata:
  name: mysql
spec:
  ports:
  - port: 3306
  selector:
    app: mysql
  type: ClusterIP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mysql
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: mysql
    spec:
      containers:
      - image: mysql:5.7.17
        name: mysql
        env:
        - name: MYSQL_ALLOW_EMPTY_PASSWORD
          value: "1"
        ports:
        - containerPort: 3306
          name: mysql
        volumeMounts:
        # Add this volume mount if you want to use the persistent storage. Apply the db-pv.yaml first
        # - name: mysql-persistent-storage
        #   mountPath: /var/lib/mysql/
        - name: mysql-host-path
          mountPath: /docker-entrypoint-initdb.d/
      volumes:
    #   - name: mysql-persistent-storage
    #     persistentVolumeClaim:
    #       claimName: mysql-pv-claim
      - name: mysql-host-path
        hostPath:
          path: /path/to/the/sql/init/script/